clone_depth: 1
version: 4.0.0.{build}

environment:
  ab_nugetserver: https://www.myget.org/F/test-test-test/
  ab_nugetkey:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  ab_s3bucket: imazen-test
  ab_s3id:
    secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  ab_s3key:
    secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0

before_build:
  - nuget restore Tools\AutoBuilder\ImageResizer.AutoBuilder.sln
  - nuget restore Core\ImageResizer.sln

build:
  project: Tools\AutoBuilder\ImageResizer.AutoBuilder.sln
  verbosity: quiet

after_build:
  - cd Tools\AutoBuilder\bin\debug
  - ImageResizer.AutoBuilder
